#include "tasmota_migrate.h"
#include "esphome/core/log.h"

#include <cstring>
#include <esp_flash.h>
#include <esp_rom_crc.h>
#include <esp_rom_md5.h>
#include <esp_system.h>

namespace esphome {
namespace tasmota_migrate {

static const char *const TAG = "tasmota_migrate";

// Flash layout constants
static const uint32_t PARTITION_TABLE_OFFSET = 0x8000;
static const uint32_t PARTITION_TABLE_SIZE = 0x1000;  // 4KB
static const uint32_t SECTOR_SIZE = 0x1000;           // 4KB

// Tasmota layout: installer runs from here
static const uint32_t TASMOTA_APP0_START = 0xE0000;

// Stock ESPHome IDF layout (generated by ESPHome's get_partition_csv)
// Offsets auto-placed: otadata, phy_init, then app0 at 64KB-aligned boundary
static const uint32_t STOCK_OTADATA_OFFSET = 0x9000;
static const uint32_t STOCK_OTADATA_SIZE = 0x2000;
static const uint32_t STOCK_PHY_INIT_OFFSET = 0xB000;
static const uint32_t STOCK_PHY_INIT_SIZE = 0x1000;
static const uint32_t STOCK_APP0_START = 0x10000;

// Partition table magic numbers
static const uint16_t PART_MAGIC = 0x50AA;

// Partition types
static const uint8_t TYPE_APP = 0x00;
static const uint8_t TYPE_DATA = 0x01;

// Partition subtypes
static const uint8_t SUBTYPE_APP_FACTORY = 0x00;
static const uint8_t SUBTYPE_APP_OTA_0 = 0x10;
static const uint8_t SUBTYPE_APP_OTA_1 = 0x11;
static const uint8_t SUBTYPE_DATA_OTA = 0x00;
static const uint8_t SUBTYPE_DATA_PHY = 0x01;
static const uint8_t SUBTYPE_DATA_NVS = 0x02;

// 64KB alignment
static const uint32_t ALIGN_64K_MASK = 0xFFFF;

float TasmotaMigrateComponent::get_setup_priority() const {
  // Run very early, before OTA and other network components
  return setup_priority::HARDWARE;
}

PartitionEntry TasmotaMigrateComponent::make_entry_(uint32_t offset, uint32_t size, uint8_t type, uint8_t subtype,
                                                     const char *label) {
  PartitionEntry e{};
  e.magic = PART_MAGIC;
  e.type = type;
  e.subtype = subtype;
  e.offset = offset;
  e.size = size;
  std::strncpy(e.label, label, sizeof(e.label));
  e.flags = 0;
  return e;
}

bool TasmotaMigrateComponent::is_tasmota_safeboot_layout_() {
  uint8_t buf[PARTITION_TABLE_SIZE];
  esp_err_t err = esp_flash_read(nullptr, buf, PARTITION_TABLE_OFFSET, PARTITION_TABLE_SIZE);
  if (err != ESP_OK) {
    ESP_LOGE(TAG, "Failed to read partition table: %d", err);
    return false;
  }

  // Scan for a factory partition labeled "safeboot"
  for (int i = 0; i < 95; i++) {
    auto *entry = reinterpret_cast<PartitionEntry *>(buf + i * 32);
    if (entry->magic != PART_MAGIC)
      break;

    if (entry->type == TYPE_APP && entry->subtype == SUBTYPE_APP_FACTORY) {
      if (std::strncmp(entry->label, "safeboot", sizeof(entry->label)) == 0) {
        ESP_LOGI(TAG, "Found Tasmota safeboot partition at 0x%06X (%uKB)", entry->offset, entry->size / 1024);
        return true;
      }
    }
  }

  return false;
}

int32_t TasmotaMigrateComponent::get_image_size_(uint32_t addr) {
  // Parse ESP-IDF image header to determine actual firmware size.
  // Format: 1 byte magic (0xE9), 1 byte segment count, then segments.
  // Each segment: 4 byte load_addr + 4 byte size, followed by `size` bytes of data.
  uint8_t header[2];
  esp_err_t err = esp_flash_read(nullptr, header, addr, sizeof(header));
  if (err != ESP_OK || header[0] != 0xE9) {
    return -1;
  }

  uint8_t seg_count = header[1];
  // First segment starts after image header (24 bytes) + segment header (8 bytes) = offset 0x20
  // But we read the segment header at seg_offset - 8
  uint32_t seg_offset = addr + 0x20;

  for (uint8_t i = 0; i < seg_count; i++) {
    uint8_t seg_header[8];
    err = esp_flash_read(nullptr, seg_header, seg_offset - 8, sizeof(seg_header));
    if (err != ESP_OK) {
      return -1;
    }
    uint32_t seg_size;
    std::memcpy(&seg_size, seg_header + 4, 4);
    seg_offset += seg_size + 8;
  }

  // Total size includes a checksum byte, round up for safety
  return static_cast<int32_t>(seg_offset - addr + 1);
}

bool TasmotaMigrateComponent::copy_firmware_(uint32_t dst, uint32_t src, uint32_t size) {
  // Copy firmware sector by sector. src and dst must not overlap.
  // This is the same approach as Tasmota's partition_wizard copy_ota().
  uint8_t buf[SECTOR_SIZE];
  uint32_t remaining = size;
  uint32_t offset = 0;

  ESP_LOGI(TAG, "Copying firmware: 0x%06X -> 0x%06X (%uKB)", src, dst, size / 1024);

  while (remaining > 0) {
    uint32_t chunk = (remaining > SECTOR_SIZE) ? SECTOR_SIZE : remaining;

    esp_err_t err = esp_flash_read(nullptr, buf, src + offset, chunk);
    if (err != ESP_OK) {
      ESP_LOGE(TAG, "Flash read failed at 0x%06X: %d", src + offset, err);
      return false;
    }

    err = esp_flash_erase_region(nullptr, dst + offset, SECTOR_SIZE);
    if (err != ESP_OK) {
      ESP_LOGE(TAG, "Flash erase failed at 0x%06X: %d", dst + offset, err);
      return false;
    }

    err = esp_flash_write(nullptr, buf, dst + offset, chunk);
    if (err != ESP_OK) {
      ESP_LOGE(TAG, "Flash write failed at 0x%06X: %d", dst + offset, err);
      return false;
    }

    remaining -= chunk;
    offset += chunk;

    if ((offset % (100 * 1024)) == 0) {
      ESP_LOGI(TAG, "Copy progress: %uKB / %uKB", offset / 1024, size / 1024);
    }
  }

  // Verify magic byte at destination
  uint8_t magic;
  esp_flash_read(nullptr, &magic, dst, 1);
  if (magic != 0xE9) {
    ESP_LOGE(TAG, "Verification failed: expected 0xE9 at 0x%06X, got 0x%02X", dst, magic);
    return false;
  }

  ESP_LOGI(TAG, "Copy complete and verified");
  return true;
}

bool TasmotaMigrateComponent::write_partition_table_(uint32_t app_size) {
  // Build stock ESPHome IDF partition table.
  // Layout matches ESPHome's get_partition_csv() for esp-idf framework:
  //   otadata, phy_init, app0, app1, nvs

  uint32_t app1_offset = STOCK_APP0_START + app_size;
  uint32_t nvs_offset = app1_offset + app_size;
  uint32_t flash_size = 0;
  esp_flash_get_size(nullptr, &flash_size);
  uint32_t nvs_size = flash_size - nvs_offset;

  ESP_LOGI(TAG, "Partition table: app0=0x%06X(%uKB) app1=0x%06X(%uKB) nvs=0x%06X(%uKB)", STOCK_APP0_START,
           app_size / 1024, app1_offset, app_size / 1024, nvs_offset, nvs_size / 1024);

  PartitionEntry entries[5];
  int n = 0;
  entries[n++] = make_entry_(STOCK_OTADATA_OFFSET, STOCK_OTADATA_SIZE, TYPE_DATA, SUBTYPE_DATA_OTA, "otadata");
  entries[n++] = make_entry_(STOCK_PHY_INIT_OFFSET, STOCK_PHY_INIT_SIZE, TYPE_DATA, SUBTYPE_DATA_PHY, "phy_init");
  entries[n++] = make_entry_(STOCK_APP0_START, app_size, TYPE_APP, SUBTYPE_APP_OTA_0, "app0");
  entries[n++] = make_entry_(app1_offset, app_size, TYPE_APP, SUBTYPE_APP_OTA_1, "app1");
  entries[n++] = make_entry_(nvs_offset, nvs_size, TYPE_DATA, SUBTYPE_DATA_NVS, "nvs");

  uint32_t entries_size = n * sizeof(PartitionEntry);

  // Compute MD5 over all entries
  uint8_t md5_hash[16];
  md5_context_t md5_ctx;
  esp_rom_md5_init(&md5_ctx);
  esp_rom_md5_update(&md5_ctx, reinterpret_cast<uint8_t *>(entries), entries_size);
  esp_rom_md5_final(md5_hash, &md5_ctx);

  // Build MD5 trailer (32 bytes)
  uint8_t md5_entry[32];
  std::memset(md5_entry, 0xFF, sizeof(md5_entry));
  md5_entry[0] = 0xEB;
  md5_entry[1] = 0xEB;
  std::memcpy(md5_entry + 16, md5_hash, 16);

  // Assemble 4KB partition table
  uint8_t table[PARTITION_TABLE_SIZE];
  std::memset(table, 0xFF, PARTITION_TABLE_SIZE);
  std::memcpy(table, entries, entries_size);
  std::memcpy(table + entries_size, md5_entry, sizeof(md5_entry));

  esp_err_t err = esp_flash_erase_region(nullptr, PARTITION_TABLE_OFFSET, PARTITION_TABLE_SIZE);
  if (err != ESP_OK) {
    ESP_LOGE(TAG, "Failed to erase partition table: %d", err);
    return false;
  }

  err = esp_flash_write(nullptr, table, PARTITION_TABLE_OFFSET, PARTITION_TABLE_SIZE);
  if (err != ESP_OK) {
    ESP_LOGE(TAG, "Failed to write partition table: %d", err);
    return false;
  }

  ESP_LOGI(TAG, "Partition table written (%d entries)", n);
  return true;
}

bool TasmotaMigrateComponent::write_otadata_(uint32_t otadata_offset) {
  // Write otadata to boot ota_0 (app0).
  // With 2 OTA partitions: (ota_seq - 1) % 2 = partition number.
  // ota_seq=1 -> (1-1) % 2 = 0 -> boots ota_0.
  uint32_t ota_seq = 1;
  uint32_t crc = esp_rom_crc32_le(0xFFFFFFFF, reinterpret_cast<const uint8_t *>(&ota_seq), sizeof(ota_seq));

  uint8_t otadata[32];
  std::memset(otadata, 0xFF, sizeof(otadata));
  std::memcpy(otadata + 0, &ota_seq, 4);
  std::memcpy(otadata + 28, &crc, 4);

  // Erase both otadata sectors
  esp_err_t err = esp_flash_erase_region(nullptr, otadata_offset, STOCK_OTADATA_SIZE);
  if (err != ESP_OK) {
    ESP_LOGE(TAG, "Failed to erase otadata at 0x%06X: %d", otadata_offset, err);
    return false;
  }

  err = esp_flash_write(nullptr, otadata, otadata_offset, sizeof(otadata));
  if (err != ESP_OK) {
    ESP_LOGE(TAG, "Failed to write otadata: %d", err);
    return false;
  }

  ESP_LOGI(TAG, "OTA data written at 0x%06X: ota_seq=1 (boot ota_0)", otadata_offset);
  return true;
}

void TasmotaMigrateComponent::setup() {
  if (!this->is_tasmota_safeboot_layout_()) {
    ESP_LOGI(TAG, "No Tasmota safeboot layout detected, nothing to do.");
    return;
  }

  ESP_LOGW(TAG, "=========================================");
  ESP_LOGW(TAG, "Tasmota safeboot layout detected!");
  ESP_LOGW(TAG, "Migrating to stock ESPHome layout...");
  ESP_LOGW(TAG, "=========================================");

  // Step 1: Detect flash size and compute app partition size
  uint32_t flash_size = 0;
  esp_err_t err = esp_flash_get_size(nullptr, &flash_size);
  if (err != ESP_OK || flash_size < 0x400000) {
    ESP_LOGE(TAG, "Flash size detection failed or too small: %u", flash_size);
    this->mark_failed();
    return;
  }
  ESP_LOGI(TAG, "Flash size: %uMB", flash_size / (1024 * 1024));

  // Stock ESPHome overhead: partitions start at 0x9000, then otadata(8KB) + phy(4KB),
  // pad to 64KB boundary = 0x10000. Add NVS at end (0x70000 for IDF).
  // app_size = ((flash - overhead) / 2) aligned down to 64KB
  uint32_t overhead = STOCK_APP0_START + 0x70000;  // 0x10000 + 0x70000 = 0x80000
  uint32_t app_size = ((flash_size - overhead) / 2) & ~ALIGN_64K_MASK;

  if (app_size < 0x80000) {
    ESP_LOGE(TAG, "App partition too small: %uKB", app_size / 1024);
    this->mark_failed();
    return;
  }

  // Step 2: Get the running firmware's actual size
  int32_t image_size = this->get_image_size_(TASMOTA_APP0_START);
  if (image_size <= 0) {
    ESP_LOGE(TAG, "Failed to determine firmware image size");
    this->mark_failed();
    return;
  }

  // Round up to sector boundary for the copy
  uint32_t copy_size = (static_cast<uint32_t>(image_size) + SECTOR_SIZE - 1) & ~(SECTOR_SIZE - 1);
  ESP_LOGI(TAG, "Firmware image size: %uKB (copy %uKB)", image_size / 1024, copy_size / 1024);

  if (copy_size > app_size) {
    ESP_LOGE(TAG, "Firmware (%uKB) doesn't fit in app partition (%uKB)", copy_size / 1024, app_size / 1024);
    this->mark_failed();
    return;
  }

  // Verify no overlap between source and destination
  uint32_t dst_end = STOCK_APP0_START + copy_size;
  if (dst_end > TASMOTA_APP0_START) {
    ESP_LOGE(TAG, "Copy destination (0x%06X-0x%06X) overlaps source (0x%06X). Cannot proceed safely.", STOCK_APP0_START,
             dst_end, TASMOTA_APP0_START);
    this->mark_failed();
    return;
  }

  // Step 3: Copy firmware from 0xE0000 -> 0x10000
  ESP_LOGW(TAG, "Copying firmware to stock app0 location...");
  if (!this->copy_firmware_(STOCK_APP0_START, TASMOTA_APP0_START, copy_size)) {
    ESP_LOGE(TAG, "Firmware copy FAILED!");
    this->mark_failed();
    return;
  }

  // Step 4: Write the stock ESPHome partition table
  if (!this->write_partition_table_(app_size)) {
    ESP_LOGE(TAG, "Partition table write FAILED!");
    this->mark_failed();
    return;
  }

  // Step 5: Write otadata to boot from the copy at 0x10000
  if (!this->write_otadata_(STOCK_OTADATA_OFFSET)) {
    ESP_LOGE(TAG, "OTA data write FAILED!");
    this->mark_failed();
    return;
  }

  ESP_LOGW(TAG, "=========================================");
  ESP_LOGW(TAG, "Migration complete!");
  ESP_LOGW(TAG, "Rebooting in 2 seconds...");
  ESP_LOGW(TAG, "After reboot, upload ESPHome firmware:");
  ESP_LOGW(TAG, "  esphome upload <config> --device <ip>");
  ESP_LOGW(TAG, "=========================================");

  delay(2000);
  esp_restart();
}

}  // namespace tasmota_migrate
}  // namespace esphome
